# Generated by Django 3.0.4 on 2021-12-06 18:59

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accidente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre Empresa')),
                ('correo', models.CharField(max_length=50, verbose_name='Correo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creacion')),
            ],
            options={
                'verbose_name': 'Accidente',
                'verbose_name_plural': 'Accidentes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('precio', models.IntegerField(blank=True, default=0, verbose_name='Precio')),
                ('desc', models.TextField(verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AsesoriaEspecial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('fecha_realizacion', models.DateField(default=datetime.datetime.now, null=True, verbose_name='Fecha de Realizacion')),
                ('inf', models.TextField(max_length=500, verbose_name='Informacion')),
                ('completado', models.BooleanField(default=False, verbose_name='Realizado')),
                ('act', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Actividad', verbose_name='Actividad')),
            ],
            options={
                'verbose_name': 'AsesoriaEspecial',
                'verbose_name_plural': 'AsesoriasEspeciales',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CheckList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('primera', models.CharField(max_length=50, verbose_name='1')),
                ('segunda', models.CharField(max_length=50, verbose_name='2')),
                ('tercera', models.CharField(max_length=50, verbose_name='3')),
                ('cuarta', models.CharField(max_length=50, verbose_name='4')),
                ('quinta', models.CharField(max_length=50, verbose_name='5')),
                ('sexta', models.CharField(max_length=50, verbose_name='6')),
                ('septima', models.CharField(max_length=50, verbose_name='7')),
                ('octaba', models.CharField(max_length=50, verbose_name='8')),
                ('novena', models.CharField(max_length=50, verbose_name='9')),
                ('decima', models.CharField(max_length=50, verbose_name='10')),
            ],
            options={
                'verbose_name': 'CheckList',
                'verbose_name_plural': 'CheckLists',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('rubro', models.CharField(max_length=150, verbose_name='Rubro')),
                ('rut', models.CharField(max_length=10, unique=True, verbose_name='Rut')),
                ('address', models.CharField(blank=True, max_length=150, null=True, verbose_name='Dirección')),
                ('cell', models.CharField(max_length=9, unique=True, verbose_name='Telefono')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=150, verbose_name='Nombre')),
                ('rut', models.CharField(max_length=10, unique=True, verbose_name='Rut')),
                ('address', models.CharField(blank=True, max_length=150, null=True, verbose_name='Dirección')),
                ('cell', models.CharField(max_length=9, unique=True, verbose_name='Telefono')),
            ],
            options={
                'verbose_name': 'Funcionario',
                'verbose_name_plural': 'Funcionarios',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.CharField(max_length=50, verbose_name='Hora')),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('desc', models.TextField(verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiales',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Profesion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('desc', models.TextField(verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Profesion',
                'verbose_name_plural': 'Profesiones',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TipoAsesoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('desc', models.TextField(verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'TipoVisita',
                'verbose_name_plural': 'TiposVista',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TipoAsesoriaEspecial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('desc', models.TextField(verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'TipoVisita',
                'verbose_name_plural': 'TiposVista',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TipoCaso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('desc', models.TextField(verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'TipoCaso',
                'verbose_name_plural': 'TipoCasos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('plan', models.TextField(max_length=400, verbose_name='Planificacion')),
                ('fecha_realizacion', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Realizacion')),
                ('sugerencia', models.TextField(blank=True, max_length=500, verbose_name='Sugerencia')),
                ('completado', models.BooleanField(default=False, verbose_name='Realizado')),
                ('act', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Actividad', verbose_name='Actividad')),
                ('ch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.CheckList', verbose_name='CheckList')),
                ('cli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Empresa', verbose_name='Cliente')),
                ('func', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Funcionario', verbose_name='Encargado')),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Horario', verbose_name='Horario')),
            ],
            options={
                'verbose_name': 'Visita',
                'verbose_name_plural': 'Visitas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=50, verbose_name='Asunto')),
                ('desc', models.TextField(max_length=500, verbose_name='Descripcion')),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('fecha_expiracion', models.DateField(default=datetime.datetime.now, verbose_name='Fecha Expiracion')),
                ('valor', models.IntegerField(default=0, verbose_name='Valor')),
                ('cumplido', models.BooleanField(default=False, verbose_name='¿Pago Realizado?')),
                ('cli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='funcionario',
            name='profesion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.Profesion', verbose_name='Profesion'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='func',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.Funcionario', verbose_name='Funcionario Asignado'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('nuevo', 'Nuevo'), ('renovado', 'Renovado')], default='Nuevo', max_length=10, verbose_name='Estado')),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('fecha_termino', models.DateField(default=datetime.datetime.now, verbose_name='Fecha Termino')),
                ('activo', models.BooleanField(default=True, verbose_name='Vigente')),
                ('emp', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='erp.Empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='checklist',
            name='cli',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Empresa', verbose_name='Empresa'),
        ),
        migrations.CreateModel(
            name='Caso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('fecha_realizacion', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Realizacion')),
                ('resultado', models.TextField(blank=True, max_length=500, verbose_name='Resultado')),
                ('completado', models.BooleanField(default=False, verbose_name='Concluido')),
                ('ase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.AsesoriaEspecial', verbose_name='Empresa')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.TipoCaso', verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Caso',
                'verbose_name_plural': 'Casos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Capacitacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('asist', models.IntegerField(default=0, verbose_name='Asistentes')),
                ('plan', models.TextField(max_length=400, verbose_name='Planificacion')),
                ('fecha_realizacion', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Realizacion')),
                ('completado', models.BooleanField(default=False, verbose_name='Realizado')),
                ('act', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Actividad', verbose_name='Actividad')),
                ('cli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Empresa', verbose_name='Cliente')),
                ('func', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.Funcionario', verbose_name='Funcionario')),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Horario', verbose_name='Horario')),
                ('mat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Material', verbose_name='Material')),
            ],
            options={
                'verbose_name': 'Capacitacion',
                'verbose_name_plural': 'Capacitaciones',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='asesoriaespecial',
            name='cli',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Empresa', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='asesoriaespecial',
            name='func',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.Funcionario', verbose_name='Funcionario'),
        ),
        migrations.AddField(
            model_name='asesoriaespecial',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.TipoAsesoriaEspecial', verbose_name='Tipo'),
        ),
        migrations.CreateModel(
            name='Asesoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('fecha_realizacion', models.DateField(default=datetime.datetime.now, null=True, verbose_name='Fecha de Realizacion')),
                ('inf', models.TextField(max_length=500, verbose_name='Informacion')),
                ('completado', models.BooleanField(default=False, verbose_name='Realizado')),
                ('act', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Actividad', verbose_name='Actividad')),
                ('cli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Empresa', verbose_name='Cliente')),
                ('func', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.Funcionario', verbose_name='Funcionario')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.TipoAsesoria', verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Asesoria',
                'verbose_name_plural': 'Asesorias',
                'ordering': ['id'],
            },
        ),
    ]
