# Generated by Django 3.0.4 on 2021-12-12 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_contacto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contacto',
        ),
    ]
