# Generated by Django 3.0.4 on 2021-12-13 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_contacto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contacto',
        ),
    ]
