# Generated by Django 3.0.4 on 2021-12-13 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_delete_contacto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre Empresa')),
                ('asunto', models.CharField(max_length=50, verbose_name='Asunto')),
                ('mensaje', models.TextField(max_length=500, verbose_name='Descripcion')),
                ('correo', models.CharField(max_length=50, verbose_name='Correo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creacion')),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
                'ordering': ['id'],
            },
        ),
    ]
