# Generated by Django 3.0.4 on 2021-12-13 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0006_contacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
    ]
