# Generated by Django 3.0.4 on 2021-12-13 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0007_auto_20211213_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='mensaje',
            field=models.EmailField(max_length=500, verbose_name='Descripcion'),
        ),
    ]
